name: νΉμ • ν‹°μ–΄ ν†µκ³„ μ—…λ°μ΄νΈ

on:
  workflow_dispatch:
    inputs:
      tier:
        description: 'μ—…λ°μ΄νΈν•  ν‹°μ–΄ (μ: challenger, gold, iron λ“±)'
        required: true

env:
  TZ: Asia/Seoul

jobs:
  update-all-tiers:
    runs-on: ubuntu-latest
    env:
      RIOT_API_KR_ROOT: ${{ secrets.RIOT_API_KR_ROOT }}
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      SERVER_URL: ${{ secrets.SERVER_URL }}
      SUMMONER_ID_FILE_PATH: "summoner_ids.txt"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6
      
      - name: Install the project
        run: uv sync --locked --no-dev

      - name: Run updates
        run: |
          INPUT_TIER="${{ github.event.inputs.tier }}"

          echo "π”„ Updating for tier: $INPUT_TIER"
          uv run src/fetch_matches.py --tier "$INPUT_TIER"
          uv run src/update_statistics.py