name: í•˜ìœ„ í‹°ì–´ ì†Œí™˜ì‚¬ ì „ì  ì—…ë°ì´íŠ¸

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ì¤‘ìœ„ í‹°ì–´ ì†Œí™˜ì‚¬ ì „ì  ì—…ë°ì´íŠ¸"]
    types:
      - completed

env:
  TZ: Asia/Seoul

jobs:
  update-all-tiers:
    runs-on: ubuntu-latest
    env:
      RIOT_API_KR_ROOT: ${{ secrets.RIOT_API_KR_ROOT }}
      RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
      SERVER_URL: ${{ secrets.SERVER_URL }}
      SUMMONER_ID_FILE_PATH: "summoner_ids.txt"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updates
        run: |
          TIERS=("gold" "silver" "bronze" "iron")

          for tier in "${TIERS[@]}"; do
            echo "ğŸ”„ Updating for tier: $tier"
            python src/fetch_summoner_id.py --tier "$tier"
            python src/update_summoner_records.py
          done